export enum AMPEventName {


    MY_CONTENT_LIST_ITEM_CLICKED,
    MY_CONTENT_CARD_CLICKED,
    MY_FOLDER_CLICKED,

    SYSTEM_CONTENT_CLICKED = 10,

    BACK_FROM_DETAIL_VIEW = 20,

    MOVE = 30,

    COPY = 40,

    CREATE = 50,

    DELETE = 60,

    SELECT_TREE_NODE = 70,

    TOGGLE = 80,

    DROPDOWN_EVENT = 90,

    CLOSE_NG_MODAL = 100,

    PUBLISH = 110,

    EDIT = 120,
    EDIT_SAVE_OUT_DATE = 121,
    UPDATE_PLAYBACK_CONTENT = 122,

    DATA_LOADING = 130, //SHOULD_BE_DELETED_ON_NEXT_RELEASED NOT BEING USED

    SEARCH_FILTER = 140,

    PRODUCT_LOADED = 150,

    NOTICE_RECEIVED = 170,

    PLAYBACK_CONTENT_REORDER_START = 180,
    PLAYBACK_CONTENT_REORDER_END = 181,
    OPEN_MASTERVIEW_FROM_DETAIL_VIEW = 182,
    
    OFFLINE_PLAYBACK,
    OFFLINE_PLAYBACK_CARD_SELECTED,
    OFFLINE_PLAYBACK_CARD_CLICKED,


    COMPONENT_IS_DIRTY,
    
    WS_EVENT = 250,
}


export enum AMPEventType {
    SELECT_LIST_ITEM,
    DESELECT_LIST_ITEM,

    OPEN_FOLDER = 10,
    CLOSE_FOLDER,

    SELECT_CARD = 20,

    MOVE_PLAYLIST = 30,
    MOVE_PROGRAMME,
    MOVE_SCHEDULE,
    MOVE_FOLDER,

    // COPY_AS_STANDARD_PLAYLIST = 40,
    // COPY_AS_ADVANCED_PLAYLIST,
    COPY_PLAYLIST = 40,
    COPY_PROGRAMME,
    // COPY_TO_MY_PLAYLISTS,
    // COPY_TO_MY_PROGRAMMES,

    CREATE_PLAYLIST = 50,
    CREATE_PROGRAMME,
    CREATE_SCHEDULE,
    CREATE_FOLDER,

    DELETE_PLAYLIST = 60,
    DELETE_PROGRAMME,
    DELETE_SCHEDULE,
    DELETE_FOLDER,

    SELECT_FOLDER_NODE = 70,

    TOGGLE_MEDIA_TYPE = 80,
    TOGGLE_CONTENT_OWNER = 81,

    CLOSE_DROPDOWN = 90,

    NAVIGATION_LINK_CLICKED = 100,

    PUBLISH_PLAYLIST = 110,
    PUBLISH_PROGRAMME,
    PUBLISH_SCHEDULE,

    EDIT_PLAYLIST = 120,
    EDIT_PROGRAMME,
    EDIT_SCHEDULE,
    EDIT_FOLDER,

    UPDATE_PLAYLIST = 124,
    UPDATE_PROGRAMME,
    UPDATE_SCHEDULE,

    DATA_LOADED = 130,

    SEARCH_FILTER_TERM = 140,


    NOTICE_SENT = 170,

    UPDATE_MASTER_SCHEDULE = 180,
    UPDATE_MASTER_PROGRAMME = 181,
    UPDATE_MASTER_PLAYLIST = 182,
    
    OPEN_MASTERVIEW = 183,
    
    OFFLINE_PLAYBACK_WS_OPEN,
    OFFLINE_PLAYBACK_WS_CHANNEL_MSG,
    PLAYBACK_WS_CHANNEL_MSG,
    OFFLINE_PLAYBACK_WS_CHANNEL_OPEN,
    OFFLINE_PLAYBACK_WS_CHANNEL_CLOSE,
    OFFLINE_PLAYBACK_WS_ERROR,
    OFFLINE_PLAYBACK_SELECTION,
    OFFLINE_PLAYBACK_TOGGLE,
    IS_MULTI_SELECT,

    COMPONENT_IS_DIRTY,
}

export interface AMPEventPayload {
    eventType?: AMPEventType,
    eventData?: any,
    params?: object
}


export interface AMPEvent {
    eventName: AMPEventName
    eventPayload: AMPEventPayload
}
